### ISSUE TITLE
IndexError: tuple index out of range in "syncacre/relay/webdav.py"

### ISSUE THREAD

**Issue by francoislaurent** [francoislaurent/syncacre#12]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "syncacre/syncacre/__main__.py", line 315, in <module>
    exit_code = main(**args.__dict__)
  File "syncacre/syncacre/__main__.py", line 262, in main
    syncacre_launcher(config)
  File "syncacre/syncacre/__main__.py", line 301, in syncacre_launcher
    syncacre(config, sections[0])
  File "syncacre/syncacre/__main__.py", line 226, in syncacre
    manager.run()
  File "syncacre/manager/manager.py", line 90, in run
    self.upload()
  File "syncacre/manager/manager.py", line 141, in upload
    remote = self.relay.listTransfered(self.dir, end2end=False)
  File "syncacre/relay/relay.py", line 299, in listTransfered
    ls = self._list(remote_dir, recursive=recursive)
  File "syncacre/relay/webdav.py", line 171, in _list
    ls = self.webdav.ls(remote_dir)
  File "Library/Python/2.7/lib/python/site-packages/easywebdav/client.py", line 176, in ls
    response = self._send('PROPFIND', remote_path, (207, 301), headers=headers)
  File "syncacre/relay/webdav.py", line 67, in _send
    info = e.args[0][1]
IndexError: tuple index out of range
```

**Comment by francoislaurent** [comment]
This issue was linked to #14. The error that syncacre.relay.WebDAVClient._send tried to handle did not come from easywebdav and therefore did not satisfy the expected format.
