### ISSUE TITLE
'module' object has no attribute 'PROTOCOL_TLSv1_1'

### ISSUE THREAD

**Issue by francoislaurent** [francoislaurent/syncacre#17]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/*/syncacre/syncacre/__main__.py", line 57, in <module>
    exit_code = main(**args.__dict__)
  File "/Users/*/syncacre/syncacre/__main__.py", line 42, in main
    syncacre_launcher(*launcher_args)
  File "syncacre/base/base.py", line 188, in syncacre_launcher
    syncacre(config, sections[0])
  File "syncacre/base/base.py", line 121, in syncacre
    manager.run()
  File "syncacre/manager/manager.py", line 82, in run
    ok = self.relay.open()
  File "syncacre/relay/webdav.py", line 187, in open
    kwargs['ssl_version'] = parse_ssl_version(self.ssl_version)
  File "syncacre/base/ssl.py", line 33, in parse_ssl_version
    'tlsv1.1':  ssl.PROTOCOL_TLSv1_1,
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_1'
```

**Comment by francoislaurent** [comment]
From https://docs.python.org/2/library/ssl.html:

> The installed version of OpenSSL may also cause variations in behavior. For example, TLSv1.1 and TLSv1.2 come with openssl version 1.0.1.

**Comment by francoislaurent** [comment]
Solved. Confirmed with version 0.3.2b1.
