### ISSUE TITLE
requests.exception.ConnectionError are not handled in relay.WebDAV

### ISSUE THREAD

**Issue by francoislaurent** [francoislaurent/syncacre#6]
Self-explaining title.

Maybe a general mechanism could be introduced so that syncacre would just wait when the relay is temporarily unavailable.

**Comment by francoislaurent** [comment]
Example error stack:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/larva/syncacre/syncacre/__main__.py", line 196, in <module>
    exit_code = main(**args.__dict__)
  File "/home/larva/syncacre/syncacre/__main__.py", line 167, in main
    syncacre(config, config.sections()[0])
  File "/home/larva/syncacre/syncacre/__main__.py", line 117, in syncacre
    manager.run()
  File "/home/larva/syncacre/syncacre/manager/manager.py", line 33, in run
    self.download()
  File "/home/larva/syncacre/syncacre/manager/manager.py", line 47, in download
    remote = self.relay.listReady(self.dir)
  File "/home/larva/syncacre/syncacre/relay/relay.py", line 63, in listReady
    ls = self._list(remote_dir, recursive=recursive)
  File "/home/larva/syncacre/syncacre/relay/webdav.py", line 44, in _list
    ls = self.webdav.ls(remote_dir)
  File "/home/larva/.local/lib/python2.7/site-packages/easywebdav/client.py", line 176, in ls
    response = self._send('PROPFIND', remote_path, (207, 301), headers=headers)
  File "/home/larva/.local/lib/python2.7/site-packages/easywebdav/client.py", line 97, in _send
    response = self.session.request(method, url, allow_redirects=False, **kwargs)
  File "/home/larva/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/larva/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/larva/.local/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(107, 'Transport endpoint is not connected'))
```

**Comment by francoislaurent** [comment]
Handled in version 0.2 with control on maximum number of retries and interval.
